### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'compat'

### ISSUE THREAD

**Issue by austsi123** [broadinstitute/badgers-cas13#5]
Thank you for working on this new tool! I really enjoyed reading the preprint about it. 

I've been working on getting this set up, but keep running into the same error in the title. This error comes up when I try to run the following: 

C:\Users\atsi\anaconda3\envs\badgers-cas13\badgers-cas13-main>python design_guides.py diff wgan_am ".\E484K_variant_identification" ".\E484K_test.tsv"

The Traceback is as follows:

Traceback (most recent call last):
  File "design_guides.py", line 32, in <module>
    from badgers.models.cas13_mult import Cas13Mult
  File "C:\Users\atsi\anaconda3\envs\badgers-cas13\badgers-cas13-main\badgers\models\cas13_mult.py", line 5, in <module>
    from badgers.utils import cas13_cnn as cas13_cnn
  File "C:\Users\atsi\anaconda3\envs\badgers-cas13\badgers-cas13-main\badgers\utils\cas13_cnn.py", line 4, in <module>
    from adapt.utils import predict_activity
  File "C:\Users\atsi\anaconda3\envs\badgers-cas13\lib\site-packages\adapt\utils\predict_activity.py", line 14, in <module>
    tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
AttributeError: module 'tensorflow' has no attribute 'compat'

I am quite inexperienced with running scripts on using Anaconda Prompt, having only used it previously to use ADAPT and it's related design scripts. Is this a common issue?

I have tried downgrading to TensorFlow 2.3.2 which is the version of the software listed as being compatible with adapt-diagnostics 1.3.0, but then receive a message that I need to upgrade it back to >=2.11 for compatibility with Tensor Probability. 

I have followed all directions to create a virtual environment and install dependencies manually using pip and am unsure where the issue lies.

**Comment by austsi123** [comment]
Was able to fix the issue by creating a new environment and doing the following:

pip install tensorflow==2.11.0
pip install flexs==0.2.8
pip install adapt-diagnostics==1.3.0
pip uninstall tensorflow==2.3.2
pip install tensorflow==2.11.0
pip install fastaparser==1.1
pip install matplotlib==3.3.4

I used the following to check that tensorflow was properly installed in between steps:
python
import tensorflow as tf
print(tf.version)

Everything seems to be working now!
